# Generated by Django 4.2.7 on 2023-11-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='graduated',
            field=models.BooleanField(default=False),
        ),
    ]
